### ISSUE TITLE
Device is rooted warning 

### ISSUE THREAD

**Issue by xxxpsyduck** [PixelExperience-Devices/device_xiaomi_wayne#2]
Some app warn me that my device is rooted and don't allow me to use. I did not root the device so the problem must come from the rom itself. Please fix this

**Comment by Hlcpereira** [comment]
> Uses custom ROMs
> Complains about some apps warn that the device is rooted and don't allow you use it

I don't know where you want to get with that, but that's the most common thing on custom ROMs, for any device.

**Comment by xxxpsyduck** [comment]
@Hlcpereira I don't know but I never had any problem with EU rom. What makes the difference?

**Comment by shreejoy** [comment]
> @Hlcpereira I don't know but I never had any problem with EU rom. What makes the difference?

Yeah then you can use it. 👍

**Comment by xxxpsyduck** [comment]
@shreejoy I am here to report an issue and I want to see if there is any solution for this. I don't know why you make a rom and don't want user to stay using it

**Comment by Hlcpereira** [comment]
Well, sorry to say that, miui based ROM have handled that in other way then. Yet those kind of stuff we aren't reponsable for, unlikely apps having Force-Closes or so. And also, those apps verify if the bootloader is unlocked, which is considered rooting also. And yet I bet it's a SafetyNet issue, If the maintainer is not looking to pass it (it's not a requirement to have SafetyNet bypass working), you can modify the prop of the build fingerprint extracting the build.prop from both vendor and system folders and "send" it back again.
